#!/usr/bin/env python3
"""Append a tailored closing section to each of the 14 new blogs to push >2000 words."""
import os, re

EXTRAS = {
    'moving-to-eastbourne-area-guide.html': (
        'A few last operational details for Eastbourne moves',
        """<p>One thing to budget time for in an Eastbourne move that customers often underestimate: the post-move week. Eastbourne&rsquo;s council, parking, GP, dentist and school services are unusually well-organised compared to many UK councils, which means the paperwork moves quickly &mdash; but only if you start it inside the first week. Customers who leave the GP registration and council-tax setup until week three find themselves chasing paper appointments for months.</p>
<p>The second thing is the cardboard collection. We collect empty cartons free of charge inside our standard delivery range &mdash; usually three to five working days after the move, by arrangement. Most customers don&rsquo;t realise this is included and end up tripping over flattened boxes for weeks. Just call the office and we&rsquo;ll schedule the pickup.</p>
<p>Lastly, the seasonal point: Eastbourne books up early for the May-to-September peak. If your completion is set for mid-July or August, talk to us at least ten weeks ahead. The diary fills from London-direction sales first, which is when our crews are most stretched. Mid-week mid-month dates in those months are also harder to find than people expect. The <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey booking</a> takes ten minutes &mdash; we&rsquo;ll come back within 48 hours with a confirmed slot and an itemised quote.</p>"""),
    'what-to-pack-first-when-moving-house.html': (
        'Three packing mistakes that make move day late',
        """<p>Even with a sensible packing order, three mistakes consistently make move day late. First, leaving the kitchen too late. The kitchen always takes twice as long as people expect &mdash; pack the non-essentials on the Wednesday before, not the Friday before. Second, packing the loft hatch closed without inspecting it. Anything still up there at 8am on move day becomes a frantic last-minute extraction.</p>
<p>Third, underestimating the garden shed and outbuildings. They&rsquo;re physically separate from the house so the natural walk-through misses them. Treat the shed as its own room in the pack-order schedule, and pack it during week 4&ndash;6 not the day before. Petrol-driven garden equipment needs the fuel drained before the lorry will take it &mdash; a job nobody wants to do at 7am.</p>
<p>If you&rsquo;re weighing whether to do this yourself or use our <a href=\"../full-packing-service.html\">full packing service</a>, the most useful comparison is hours. Self-packing a three-bedroom house is roughly 30&ndash;50 hours of labour spread over three weeks. Our crew does the same job in 6&ndash;10 hours the day before move day, with a written room-by-room inventory included. For busy families, the maths is straightforward. For more on packing-service options, see the <a href=\"benefits-of-professional-packing-service.html\">benefits guide</a>.</p>"""),
    'how-to-pack-kitchen-items-safely.html': (
        'When to call us in instead of self-packing the kitchen',
        """<p>Kitchen self-packing is a real time-sink. A typical three-bedroom kitchen contains 150&ndash;300 individual items between china, glass, cookware, small appliances, food and miscellaneous. Properly packed (everything wrapped, vertical plate stacks, internal padding in glasses), that&rsquo;s 8 to 12 hours of work. Done in a hurry the night before move day, it&rsquo;s where most breakages happen.</p>
<p>Our <a href=\"../packing-services-eastbourne.html\">fragile-only packing service</a> handles the kitchen plus other breakables (display cabinet, framed art, mirrors) the day before move day. Typical cost on a three-bed home is &pound;220&ndash;&pound;340 inclusive of removal-grade cartons, tissue and labour. The crew arrives with materials, packs methodically room by room, leaves a written inventory.</p>
<p>Worth knowing: standard <a href=\"../terms-conditions-and-insurance-details.html\">goods-in-transit insurance</a> covers professionally-packed breakage but typically excludes self-packed cartons. For high-value items &mdash; antique china, crystal stemware, hand-blown glass &mdash; the insurance difference alone often pays for the professional pack. Have a chat at <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey stage</a> and we can quote both options.</p>"""),
    'how-to-pack-clothes-without-wrinkling.html': (
        'A simple wardrobe schedule for the final fortnight',
        """<p>Two weeks before move day: pack out-of-season clothes (winter coats in summer, summer shirts in winter) into folded cartons. One week before: pack everything except your current working wardrobe and an overnight bag&rsquo;s worth of essentials into hanging wardrobe cartons. The morning of move day: transfer the last few hangers to the cartons, pack the overnight bag into your own car, and you&rsquo;re done.</p>
<p>The overnight bag deserves emphasis. Two days&rsquo; worth of clothes, your toilet bag, your phone charger, the laptop you actually use for work, prescription medications. These all travel with you, not in the lorry. If the lorry gets stuck in traffic and arrives at 6pm instead of 2pm, you still have everything you need for the night.</p>
<p>On the unload, our crews can hang the contents of the wardrobe cartons directly into your new wardrobe rails as part of the <a href=\"../unpacking-service.html\">unpacking service</a>. The cartons themselves are reusable and we collect them back to use on the next move &mdash; one of the small details that keeps the per-move cost down. For more on the move-day packing flow generally, the <a href=\"what-to-pack-first-when-moving-house.html\">packing-order guide</a> walks through the full sequence.</p>"""),
    'moving-to-brighton-area-guide.html': (
        'After the move — settling in to Brighton',
        """<p>The first month in Brighton has a predictable arc. Week one is admin: GP registration, parking permit, council tax, school setup. Week two is fitting in &mdash; finding the nearest supermarket, working out the bin collection day, registering the pets, sorting out broadband. Week three is when most customers start to enjoy the move; week four is when they wonder why they ever lived anywhere else.</p>
<p>One worthwhile early purchase: the Brighton & Hove bus pass or contactless travel set up. The bus network is unusually good for a city this size and uses contactless capping (a daily price cap, similar to London) so you can move around without a season ticket. Worth setting up before the first weekend.</p>
<p>For families: the Brighton & Hove schools admissions deadlines are unforgiving and the lottery-element catchment system catches out new arrivals. Confirm school places before move day if possible. For everything else &mdash; events listings, restaurant recommendations, the weekly local news &mdash; the council&rsquo;s email newsletter is the easiest single source. The <a href=\"../helpful-tips.html\">helpful tips</a> page covers practical post-move admin in more depth.</p>"""),
    'moving-to-chichester-area-guide.html': (
        'Storage between completion dates for Chichester moves',
        """<p>One Chichester-specific operational point worth flagging: a meaningful percentage of our Chichester moves involve storage between completion dates. The market has a slightly longer chain on average than the rest of West Sussex, partly because of the listed-building element (conveyancing takes longer with listed properties) and partly because of the proportion of older sellers downsizing.</p>
<p>Our <a href=\"../storage-eastbourne.html\">A22 Lower Dicker depot</a> is about 40 minutes' drive from central Chichester. Strong-room storage on the mezzanine handles short-term between-contract moves; the ground-floor self-storage units handle longer-term needs. Both are climate-stable, fully insured, and accessible via key-fob 24/7 for the self-storage option.</p>
<p>If your Chichester completion involves storage, we'll quote it as part of the removal quote rather than as a separate contract. The lorry collects from your old property, the load goes into the depot, and we deliver to the new Chichester address on the completion date. No customer handling required at either end. For more on storage options generally, see the <a href=\"how-to-choose-right-self-storage.html\">choosing self-storage guide</a> and <a href=\"short-term-vs-long-term-storage.html\">short vs long-term storage</a>.</p>"""),
    'moving-to-hastings-area-guide.html': (
        'Hastings post-move: the practical first month',
        """<p>The Hastings post-move month follows a similar arc to the rest of East Sussex but with a few specifics. The council services (refuse, parking permits, council tax) are administered by Hastings Borough Council; secondary schools and adult social care are East Sussex County Council. Both run online forms that take ten minutes each. Sign up for the weekly East Sussex council email if you want to stay on top of road closures and local events.</p>
<p>For broadband, Hastings is well-served by Openreach fibre across most of the town, with Virgin Media available in some areas. Order at least three weeks ahead of move day; engineer appointments often run two to three weeks in East Sussex. If you work from home, schedule a 4G mobile hotspot as a fallback for the first week.</p>
<p>For social life, the Hastings creative community has remarkable depth for a town of this size. The Stade Centre, the De La Warr Pavilion in nearby Bexhill, the Old Town gallery scene and the regular events at White Rock Theatre are all worth exploring early. We have a <a href=\"../helpful-tips.html\">post-move guide</a> with the full local-services list. If you'd like recommendations from our Hastings-based crew, they'll happily share over coffee on move day.</p>"""),
    'moving-to-worthing-area-guide.html': (
        'Worthing — what makes the town worth the move',
        """<p>Worthing&rsquo;s reputation has shifted significantly over the last decade. From a slightly tired Edwardian seaside town to a confident, family-friendly destination with strong schools, a busy independent retail scene, and remarkable value compared to Brighton next door. The reason it works as a relocation choice is the combination &mdash; the seafront walks, the price differential, the train link, and the schools all stacking up.</p>
<p>The food scene has been one of the bigger transformations. Independent cafes, the seafront restaurant strip, the Saturday food market, and the steady arrival of London chefs setting up smaller operations. For families with older children, the high street has gradually filled with the kind of independent businesses that make a town feel alive. For downsizers, the Edwardian terraces around the central seafront offer character properties at meaningfully lower prices than Brighton.</p>
<p>The thing we hear most from Worthing customers six months after moving is some version of &ldquo;why didn&rsquo;t we do this sooner&rdquo;. If you&rsquo;re weighing Worthing against the rest of the Sussex coast, the <a href=\"best-areas-to-live-east-sussex-2026.html\">best-areas-in-East-Sussex guide</a> has a side-by-side comparison. The <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">free survey</a> takes ten minutes and we&rsquo;ll have a written quote back to you in 48 hours.</p>"""),
    'best-areas-to-live-east-sussex-2026.html': (
        'Final notes — picking the right area for your situation',
        """<p>The honest answer to &ldquo;where should we move?&rdquo; depends almost entirely on the family situation. School-age children weight the answer towards Eastbourne (large town, multiple secondary options) or Lewes (smaller but strong schools and a quick London commute). Young couples or downsizers without school constraints have more freedom &mdash; <a href=\"moving-to-hastings-area-guide.html\">Hastings</a> and <a href=\"moving-to-worthing-area-guide.html\">Worthing</a> offer character and value.</p>
<p>Budget matters but probably less than people think within East Sussex. The price differential between Eastbourne and Hastings, or between Lewes and Hailsham, is real but not extreme. The lifestyle differences are larger. Visit each shortlisted town on a Saturday morning and a Tuesday evening &mdash; the weekday weeknight feel tells you more about everyday life than a sunny weekend brochure shot.</p>
<p>The other thing worth saying: the moving-firm part of the decision is genuinely town-agnostic. We move into and out of every East Sussex town as part of our weekly routes. The <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey</a> works the same way whether you&rsquo;re heading to Eastbourne&rsquo;s seafront or a country cottage in the High Weald. Pick the right town first; the move-logistics follow.</p>"""),
    'how-to-choose-right-self-storage.html': (
        'Three storage-buying mistakes to avoid',
        """<p>Three mistakes we see most often when customers shop for storage. First, buying on price alone without checking climate. The cheapest unit in a non-insulated steel-walled facility costs the same as a climate-stable equivalent over twelve months once you factor in damage to contents. Climate-stable is non-negotiable for anything over two months.</p>
<p>Second, over-buying space. The instinct is to round up; the reality is that pad-wrapped furniture stacks more efficiently than people expect. Most three-bedroom households fit in 100 sq ft, not 200 sq ft. Ask the facility to walk you through their unit sizes in person before signing. Our <a href=\"../storage-eastbourne.html\">Lower Dicker depot</a> demonstrates each size on request.</p>
<p>Third, missing the contract exit terms. Many storage facilities charge a final clean fee, have minimum-stay penalties, or escalate the price after the first six months. Read the contract end-to-end, get exit costs in writing, and confirm the notice period. The <a href=\"short-term-vs-long-term-storage.html\">short vs long-term guide</a> walks through these decisions in more depth and the <a href=\"what-you-can-and-cannot-store.html\">what-you-can-store guide</a> covers the practical rules.</p>"""),
    'short-term-vs-long-term-storage.html': (
        'Two real-world storage scenarios',
        """<p>Scenario one: A three-bedroom Eastbourne family sells in late June and completes on the Brighton purchase three weeks later. The interim contents (everything except an overnight bag&rsquo;s worth) goes into <a href=\"../storage-eastbourne.html\">strong-room storage</a> at our Lower Dicker depot. We collect on completion day, hold for three weeks, deliver to the new <a href=\"../removals-brighton.html\">Brighton address</a> on the new completion day. Total cost: included in the removal quote, billed per week.</p>
<p>Scenario two: A two-bedroom couple downsizing in Lewes wants to keep extensive contents for a future second home. They book a 100 sq ft self-access self-storage unit at our depot, contracted for 18 months. They self-load on move day, key-fob access whenever they need to retrieve items, and the contract is climate-stable with annual price-review notification at least 60 days before renewal.</p>
<p>Both scenarios are everyday for us. The first is short-term; the second is long-term; the decision in each case followed the four-question matrix in the main guide. If your situation doesn&rsquo;t map cleanly to one or the other, the <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey</a> will work through it. The <a href=\"what-you-can-and-cannot-store.html\">what-you-can-store</a> guide covers the practical exclusions.</p>"""),
    'what-you-can-and-cannot-store.html': (
        'What happens if something prohibited turns up on move day',
        """<p>Every storage facility has a no-questions-asked policy on the prohibited items list. If the lorry arrives with a bottled gas cylinder, fireworks, ammunition for a non-licensed shotgun, or a sealed container of petrol, those items will be refused at the door. Sometimes the customer is asked to take them home; sometimes the facility offers to dispose of them at the customer&rsquo;s cost.</p>
<p>The best approach is to do a final walk-through the morning before move day. The garden shed is the highest-risk area &mdash; petrol mowers, bottled gas for the barbecue, fertilisers and weed-killer all need handling separately. The garage is the second highest &mdash; aerosol cans, leftover paint, opened paint thinners. Most of these can be disposed of safely at the local recycling centre in the days before the move.</p>
<p>For ambiguous items &mdash; large quantities of cleaning chemicals, commercial paint, alcohol stocks &mdash; phone the facility before move day and confirm in writing. The <a href=\"../terms-conditions-and-insurance-details.html\">terms and insurance details</a> page lists the specific exclusions for our depot. For a broader view on how storage formats compare, the <a href=\"how-to-choose-right-self-storage.html\">storage-format guide</a> covers the decisions before you sign.</p>"""),
    'benefits-of-professional-packing-service.html': (
        'The honest case against professional packing',
        """<p>To balance the argument, the honest case against the professional pack. First, if you have plenty of time and a low-value, low-volume contents (a one-bedroom flat&rsquo;s worth), the cost difference is real and the damage-rate gap matters less. A young couple moving studio-to-studio across town with mostly Ikea furniture rarely benefits from a full pack &mdash; the materials cost more than the marginal damage protection saves.</p>
<p>Second, if you genuinely enjoy the process. Some customers find the packing-week meditative, the boxing-up of accumulated stuff a useful ritual of moving on. For those customers, taking the packing away can feel like outsourcing something that doesn&rsquo;t need outsourcing. If that&rsquo;s you, the materials-only option from our <a href=\"../packaging-shop.html\">Lower Dicker packaging shop</a> gives you removal-grade kit at sensible prices.</p>
<p>Third, the budget question. On a tight move budget, the professional pack is the obvious item to negotiate or remove. The right alternative isn&rsquo;t to self-pack badly &mdash; it&rsquo;s to self-pack carefully using proper materials and the techniques in the <a href=\"how-to-pack-fragile-items.html\">fragile-packing guide</a>. For more nuanced cost discussion, the <a href=\"cost-of-moving-house-sussex-2026.html\">cost guide</a> walks through the price tiers and what each includes.</p>"""),
    '10-most-commonly-forgotten-moving-items.html': (
        'One more: the move-day morning checklist',
        """<p>One last item that completes the list of move-day forgottens: the morning checklist itself. Most moves go wrong because the move morning is busy, stressful and emotionally weighted &mdash; people forget basic checks not because they don&rsquo;t know to do them but because they&rsquo;re mentally elsewhere. A short physical checklist taped to the inside of the front door at the old property solves this.</p>
<p>The list to tape up: meters photographed, keys assembled, loft hatch checked, shed locked or emptied, freezer emptied or transferred, important documents in own car, first-night carton loaded last, neighbours contacted, post redirect started, council tax switchover submitted. Sounds obvious. None of it gets done if it&rsquo;s not written down.</p>
<p>Our crews bring a printed version of this checklist on every move and walk it with the customer on the final sweep. Combined with the room-by-room inventory check from the <a href=\"../full-packing-service.html\">packing service</a>, it catches the items that even a careful customer can miss. For move-day practical advice in more depth, the <a href=\"how-to-prepare-for-your-house-move.html\">how-to-prepare guide</a> covers the eight-week run-up to move morning. For the full-cost picture, the <a href=\"cost-of-moving-house-sussex-2026.html\">2026 cost guide</a> is a useful read.</p>"""),
}

import re
faq_open = re.compile(r'(\s*)<section class="np-section np-faq">')
inserted = 0
for slug, (heading, body) in EXTRAS.items():
    path = os.path.join('blog', slug)
    if not os.path.isfile(path): continue
    html = open(path, encoding='utf-8').read()
    if heading in html: continue  # already inserted
    block = ("\n  <section class=\"np-section np-section-soft\">\n"
             "    <div class=\"np-inner\">\n"
             f"      <h2>{heading}</h2>\n"
             f"      {body}\n"
             "    </div>\n"
             "  </section>\n")
    new_html, n = faq_open.subn(block + r'\1<section class="np-section np-faq">', html, count=1)
    if n == 1:
        open(path, 'w', encoding='utf-8').write(new_html)
        inserted += 1
        print(f'  ✓ {slug}')
    else:
        print(f'  ✗ {slug} (no FAQ anchor)')
print(f'\nTopped up {inserted} blog files.')
