#!/usr/bin/env python3
"""Add substantial extra content to the 19 short blogs."""
import os, re

# Topic-specific extra section blocks (~250-350 words each, varied per topic)
EXTRAS = {
    'antique-furniture-moving-specialist.html':
        ('Specialist storage for antiques during moves',
         """<p>A meaningful share of antique-heavy moves involve storage between completion dates. Antiques particularly need climate-stable conditions &mdash; uninsulated steel-walled storage units cause condensation that damages veneer and warps wood within weeks, not months. Our <a href=\"../storage-eastbourne.html\">Lower Dicker depot</a> has climate-stable strong-room storage on the mezzanine designed specifically for high-value content holding.</p>
<p>For collection-level holds (a full art collection, a set of family silver, an antique furniture inventory waiting for a future property purchase), our <a href=\"prestige-steel-storage-rooms.html\">Prestige Steel Storage Rooms</a> are the relevant tier. Individual rooms inside our secure depot, climate-controlled, with formal inventory tracking and access management. Cost is meaningful relative to standard self-storage but appropriate for the value of what&rsquo;s stored.</p>
<p>For shorter holds (between-completion contingency, brief renovation period at the new property), standard depot storage works fine. The <a href=\"short-term-vs-long-term-storage.html\">short-vs-long-term storage guide</a> covers the decision framework. For genuinely valuable items going into long-term storage, the climate-stable conditions matter more than the cost differential.</p>
<p>For pre-storage preparation, the <a href=\"how-to-prepare-furniture-for-storage.html\">preparing furniture for storage guide</a> covers the cleaning, wrapping and material choices that prevent damage during the storage period. None of this is complicated but the difference between &ldquo;stored well&rdquo; and &ldquo;stored carelessly&rdquo; shows up at the retrieval end six months or two years later.</p>"""),
    'business-office-relocation.html':
        ('Specialist office equipment and the IT-storage question',
         """<p>Beyond the standard office contents, several specialist categories warrant specific planning. <strong>Server racks</strong>: substantial weight, careful pre-disconnection by your IT team, lifting equipment for the larger racks. We move the physical equipment; your IT team handles the connectivity setup at the new site. The <a href=\"how-to-pack-electronics-safely.html\">packing electronics guide</a> covers the workstation-level packing.</p>
<p><strong>Commercial safes and document storage</strong>: weight and security considerations. The <a href=\"heavy-item-moves-pianos-safes.html\">heavy items guide</a> covers safe-moving methods. For genuinely secure document holding (legal firms, accountants, healthcare records), we coordinate with specialist secure-document carriers where appropriate.</p>
<p>For offices reducing in size, the <a href=\"../storage-eastbourne.html\">Lower Dicker storage</a> handles overflow contents that don&rsquo;t fit the new layout. Commercial storage contracts work the same as residential: climate-stable strong-room storage or self-access self-storage depending on the access frequency. For business-stock holdings (e-commerce inventory, sample stock, archived files), the format choice matters; the <a href=\"how-to-choose-right-self-storage.html\">choosing storage guide</a> covers it.</p>
<p>For multi-site businesses or office relocations involving phased moves across multiple weeks, the survey conversation gets longer than for a single-day office move. Talk to us at <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey</a> early in the planning &mdash; ideally before the new lease is signed &mdash; and we&rsquo;ll help structure the timeline.</p>"""),
    'carbon-neutral-moves-explained.html':
        ('Working out the residual carbon and where to offset it',
         """<p>Once the reduction work is done (declutter, choose local where possible, reusable materials), the remaining footprint sits at typically 60&ndash;80% of the unoptimised baseline. For a typical Sussex 3-bed local move, that&rsquo;s 70&ndash;110 kg CO2-eq residual. For a London-to-Sussex move, 250&ndash;350 kg residual. For international moves, the residual is dominated by the shipping leg.</p>
<p>For UK-based offset purchasers, the Woodland Carbon Code is one of the more credible single options &mdash; verified, ongoing-monitored, domestic woodland creation. For international preference, Gold Standard schemes are the standard. The choice between domestic and international offsets matters less than the verification quality.</p>
<p>For ongoing carbon accounting (households committed to longer-term net-zero), the move-specific offset is one item among several. The wider household-emissions categories (commuting, flights, home heating) typically dominate annual totals. Our <a href=\"sustainable-removals-guide.html\">sustainable removals guide</a> covers the move-side practices in more detail.</p>
<p>For customers who want offsetting included in the move quote, we&rsquo;ll arrange it through a verified provider and add it as a line item on the quote. The certificate of retirement comes back to you after the move &mdash; PDF or paper, with the project ID, the registry number, and the CO2-eq amount retired. Keep the certificate for any future sustainability accounting.</p>
<p>The honest framing: carbon-neutral isn&rsquo;t a magic label that erases environmental impact. Offsets handle the climate-specific footprint but not the broader environmental aspects. For a genuinely sustainable move, reduction comes first, offsetting comes second. The combination delivers a measurably greener move than the industry baseline. Talk to us at <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey</a> if you&rsquo;d like the move handled this way.</p>"""),
    'care-home-relocation-guide.html':
        ('Regulatory framework, CQC and the inspection process',
         """<p>Care home relocations sit inside a regulatory framework that adds requirements no ordinary residential move involves. <strong>CQC notification</strong> (the Care Quality Commission) needs at least 28 days&rsquo; written notice of any change in registered location. For the move itself, the registered manager files a notification of change with CQC; the new location may require a fresh CQC inspection before regulated activities can recommence there.</p>
<p><strong>Local authority adult social-services teams</strong> need coordination for the residents whose placements they fund. Each funded resident&rsquo;s care plan may need updating to reflect the new location, the new GP relationship, and any changes in care arrangements. For privately-funded residents the equivalent conversations happen with families.</p>
<p><strong>Insurance arrangements</strong> shift with the move &mdash; building insurance, public liability, employer&rsquo;s liability, professional indemnity. Confirm coverage at both sites during the transition period; brief gaps in coverage can have serious legal consequences.</p>
<p>For the practical move-day coordination, the regulatory layer means our crew works alongside care-home managers and local-authority liaison officers. Daily briefings during the transition period are non-negotiable. The <a href=\"business-office-relocation.html\">business relocation guide</a> covers parallel coordination principles for commercial moves; care-home moves add the human-services dimension on top.</p>
<p>For pre-move planning, allowance for unscheduled delays is essential. A resident may have a medical event during the transition that requires the move plan to flex by 24&ndash;72 hours; the family of an anxious resident may request a different transfer day at short notice. Rigid scheduling doesn&rsquo;t work for care home moves; flexible planning is part of the service.</p>"""),
    'christmas-new-year-house-move.html':
        ('Working backwards from the Christmas Day arrangements',
         """<p>For families committed to a festive-period move, the planning sequence is genuinely backwards from how a normal move plan works. Most house moves start with the date and work outwards. Festive moves start with the Christmas Day arrangements and work backwards to the move date.</p>
<p>The Christmas Day arrangements matter because they&rsquo;re fixed and emotionally weighted. The family is hosting in-laws on December 25th; the children expect Father Christmas to arrive at the new house; the religious or cultural observance is non-negotiable. Once these are decided, the move date works around them. Move on December 22nd: unpacking through the 23rd, Christmas Eve traditions on the 24th, Christmas Day at the new house.</p>
<p>For the operational side, plan a low-bar &ldquo;unpacked enough&rdquo; standard. The kitchen needs to be functional for cooking (saucepans, plates, cutlery, basic ingredients). The bedrooms need beds made up. The dining table needs to be ready. Everything else can wait until January.</p>
<p>For the children specifically, the <a href=\"moving-house-with-children.html\">moving with children guide</a> covers the family logistics. Pre-arrange childcare or family hosting for move day. Decorations and Christmas-tree assembly can happen on December 23rd if needed; some families do this together as part of the moving-in ritual.</p>
<p>For families with pets, the <a href=\"moving-house-with-pets.html\">moving with pets guide</a> applies; the festive period adds emotional load that can stress animals further. Boarding kennels and friends-pet-sitting both work; choose ahead of time.</p>
<p>The honest reality: a successful Christmas move is the one where realistic expectations get set early. The first Christmas in the new place won&rsquo;t look like a magazine spread. That&rsquo;s fine. Customers who manage their expectations are consistently the ones who report the calmest festive moves.</p>"""),
    'cleaning-checklist-moving-out.html':
        ('Professional cleaning services and the deposit-return calculation',
         """<p>For end-of-tenancy moves where the deposit is at stake, hiring a professional cleaner is almost always the better choice than DIY. Cost: typically &pound;100&ndash;&pound;200 for a one-off end-of-tenancy clean. Time saved: 5&ndash;8 hours of customer labour. Risk reduced: the professional&rsquo;s receipt becomes evidence in any deposit dispute.</p>
<p>The professional clean covers the standard checklist: oven (interior deep clean), all kitchen cabinets, fridge and freezer (defrosted), bathrooms (limescale, grout, tiles, toilet), all carpets vacuumed and spot-cleaned, all surfaces dusted and wiped, windows interior, light switches and door handles. The standard takes a professional team 3&ndash;5 hours for a typical 3-bedroom property.</p>
<p>For owner-moves where there&rsquo;s no deposit at stake, DIY is fine and the goodwill standard is what matters. The new buyer wants a clean property at completion; perfectly-professional standard is appreciated but not required. Plan to do the clean the day after move day in an empty house: kitchen and bathrooms in the morning, bedrooms and living rooms in the afternoon.</p>
<p>For specific high-deposit-risk items (the oven, the carpets, the bathroom limescale), specialist services exist. Oven-cleaning services (&pound;50&ndash;&pound;100) handle the worst-case oven faster than DIY. Carpet-cleaning services (&pound;30&ndash;&pound;60 per carpet) deliver visibly-better results than DIY shampooing.</p>
<p>For coordinating with the move day itself, schedule the cleaning service for the afternoon after the lorry leaves. By 5pm the property is empty; the cleaning team starts at 5:30pm and finishes by 9pm. Keys go back to the agent the following morning with a clean property and the cleaning receipt. The <a href=\"how-to-prepare-for-your-house-move.html\">how-to-prepare guide</a> covers the wider scheduling.</p>"""),
    'diy-move-vs-professional.html':
        ('The middle-ground hybrid options',
         """<p>Beyond the binary DIY-vs-professional choice, several hybrid options work well for specific situations. <strong>Man-and-van with self-pack</strong>: we provide two crew and a van; you pack and supervise. Pricing on a typical Sussex job runs &pound;200&ndash;&pound;500 for a half-day or full day. Good for studio flats and 1-bed moves where the lifting is the difficult part and the packing is doable.</p>
<p><strong>Full removal with fragile-only packing</strong>: we handle the entire move plus pack the breakables (kitchen, display cabinet, framed art, mirrors); the customer self-packs the easy categories (books, clothing, linen, garage). On a typical 3-bed home, this saves &pound;200&ndash;&pound;400 versus a full pack without the damage-rate concern on the self-packed easy stuff. The <a href=\"benefits-of-professional-packing-service.html\">packing-service guide</a> covers the comparison.</p>
<p><strong>Full removal with materials-only packing</strong>: we deliver removal-grade cartons, tape, bubble and tissue; the customer packs everything; we handle the move itself. Cheapest professional tier on the move side; self-packing damage risk on the customer side. Works well for low-value contents and customers with time to pack properly.</p>
<p><strong>Full pack and full move</strong>: the customer&rsquo;s job becomes management rather than physical work. Highest cost but lowest customer effort. For customers in genuinely time-pressured situations, the right tier.</p>
<p>The right choice depends on the move size, the contents value, the customer&rsquo;s time and physical capacity, and the budget. There&rsquo;s no universal right answer; the survey conversation is where it gets settled. The <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">free survey</a> covers the tier-by-tier breakdown.</p>"""),
    'essential-moving-day-survival-kit.html':
        ('Survival-kit variations by move type',
         """<p>The standard survival-kit list works for most house moves but several move types benefit from specific additions. <strong>Long-distance moves</strong>: add a packed lunch and dinner, sufficient hydration for the journey, a separate &ldquo;hotel night&rdquo; bag if the move involves an overnight stop, and any prescription medications for an extra day&rsquo;s worth.</p>
<p><strong>Family moves with young children</strong>: add specific children&rsquo;s items &mdash; the favourite teddy, two books, a small toy, the children&rsquo;s overnight clothes, snacks they actually eat. The <a href=\"moving-house-with-children.html\">moving with children guide</a> covers the broader family-side planning. Children handle the move better when their familiar items arrive with them.</p>
<p><strong>Moves with pets</strong>: the pet&rsquo;s entire daily kit (food, water bowl, leash, favourite toy, carrier for cats, blanket from old house, medications). The <a href=\"moving-house-with-pets.html\">moving with pets guide</a> covers the wider pet considerations.</p>
<p><strong>International moves</strong>: add documentation specific to the destination (visa paperwork, return-flight confirmations if temporary, hotel booking for the destination), local currency for the first 24 hours, and a small kit of products that may be hard to find at the destination.</p>
<p><strong>Solo moves</strong>: add comfort items for the first night alone in the new property (a book or two, a hot-water bottle, a particular comfort food). Solo movers benefit more than family movers from the small things that make the first night feel like home rather than a campsite.</p>
<p>The single most overlooked addition across all categories: a charged phone power bank. One phone charger always gets misplaced on every move; having a spare prevents the &ldquo;phone died at 7pm&rdquo; failure mode. Worth the &pound;10&ndash;&pound;15 cost.</p>"""),
    'fine-art-moving-guide.html':
        ('Art-specific storage and the long-distance question',
         """<p>For art moves involving storage between completion dates, climate-controlled storage matters more than for ordinary household contents. Humidity swings cause canvas to slacken, panel paintings to warp, and varnish to bloom over weeks. Our <a href=\"../storage-eastbourne.html\">Lower Dicker depot</a> is climate-stable for ordinary household contents; for genuinely valuable art collections we coordinate with specialist art-storage providers who offer precise humidity regulation.</p>
<p>For long-distance art moves (London to Sussex, or further), the route planning matters. We schedule the lorry routing to minimise temperature exposure &mdash; early morning starts in summer, sheltered overnight parking where overnight stops happen, climate-controlled vehicles for the longest-distance moves. For international art moves, the FIDI-network partners we work with maintain climate-controlled containers throughout the shipping leg.</p>
<p>For pre-move documentation, photograph and inventory everything before move day. Wide shots of each piece, close-ups of signatures and marks, current condition of any pre-existing chips or restoration work. This documentation is invaluable in any future insurance discussion and worth thirty minutes of your time.</p>
<p>For after-move care, art collections benefit from being unpacked and inspected within 48 hours of arrival. Any transit damage shows up most clearly during the inspection. Document any concerns immediately and contact us; insurance claims process much faster when reported within days rather than weeks.</p>
<p>For ongoing care at the new property, climate stability matters. Avoid mounting valuable art on external walls (more humidity variation), avoid direct sun on framed works (causes fading and varnish deterioration), avoid mounting art directly above radiators (heating cycles affect canvas tension). The <a href=\"moving-antiques-valuable-furniture.html\">antiques moving guide</a> covers parallel considerations for antique furniture.</p>"""),
    'heavy-item-moves-pianos-safes.html':
        ('Grandfather clocks and other timepieces',
         """<p>Grandfather clocks deserve their own paragraph because they&rsquo;re moved differently from other heavy items and the damage potential from doing it wrong is high. The clock has three components that need separate handling: the case (the wooden cabinet, often Victorian or Edwardian), the movement (the mechanical timekeeping mechanism), and the pendulum and weights (the heavy brass cylinders that drive the mechanism).</p>
<p>Before any move, the pendulum is removed and packed separately (wrapped in soft cloth, vertical orientation in a custom carton). The weights are removed and packed separately too (heavy bubble wrap, individually padded). The movement is sometimes removed from the case for high-value clocks; for ordinary domestic grandfather clocks the movement stays in the case but the movement is stabilised with packing tissue to prevent the pendulum hook from swinging.</p>
<p>The case itself is pad-wrapped using our standard <a href=\"how-our-pad-wrap-service-protects-furniture.html\">pad-wrap method</a> with additional protection on the glass front panel. The case travels upright, never on its back &mdash; the gravity-loaded movement components are designed for vertical orientation.</p>
<p>At the new property, reassembly happens in the destination room. The weights and pendulum are reattached; the clock is wound and started. Most grandfather clocks need 24&ndash;48 hours to settle before keeping accurate time; ours and most other reputable removers&rsquo; quotes include the reassembly time at the unload.</p>
<p>For valuable antique clocks (Tompion, Knibb, named-maker grandfather clocks worth above &pound;10,000), specialist horological transport is sometimes the right answer rather than general removal. We&rsquo;d advise at <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey</a> based on the specific clock. Other timepieces (carriage clocks, mantel clocks, longcase clocks of modest value) are handled within standard antique-furniture protocols.</p>"""),
    'how-to-avoid-moving-scams.html':
        ('Bank-card protection and consumer rights',
         """<p>For payment protection specifically, the payment method makes a meaningful difference if things go wrong. <strong>Credit card</strong>: Section 75 of the Consumer Credit Act covers purchases between &pound;100 and &pound;30,000 made on a UK credit card. If the seller (the removal firm) fails to deliver the service, the card issuer is jointly liable with the seller. This is the strongest single consumer protection for higher-value transactions.</p>
<p><strong>Debit card</strong>: chargeback protection through Visa/Mastercard schemes. Less robust than Section 75 but covers most scenarios where the service wasn&rsquo;t delivered or was significantly different from what was paid for. Time-limited (typically 120 days) so action needs to be prompt.</p>
<p><strong>Bank transfer</strong>: no automatic protection but the transaction is traceable. The bank may be able to recall the transfer if reported quickly and the recipient bank cooperates; in practice this is rare for scam scenarios where the money has already moved.</p>
<p><strong>Cash</strong>: no protection whatsoever. Once paid, cash is essentially irrecoverable through consumer channels. The police can investigate if the operator is identifiable, but cash transactions are by design difficult to prove.</p>
<p>For larger removal payments (above &pound;100, certainly the deposit and the balance), use a credit card if at all possible. The Section 75 protection alone is worth more than the small admin friction of credit-card payment. For BAR-registered firms the deposit is also APG-protected, giving belt-and-braces coverage that&rsquo;s essentially impossible to lose money on.</p>
<p>For the actual transaction, ensure the firm name on the card statement matches the firm name on the quote and the contract. Discrepancies here can complicate any future Section 75 claim. Our <a href=\"../terms-conditions-and-insurance-details.html\">terms and insurance details</a> page shows what a transparent firm&rsquo;s payment arrangements look like.</p>"""),
    'licensed-premises-relocation.html':
        ('Stock transfer, brewery accounts and the financial transition',
         """<p>Pub and restaurant moves have a financial-transition layer that ordinary commercial moves don&rsquo;t. Beer stock, wine and spirit stock, food stock, kitchen consumables &mdash; all of these have value and all need handling around the move date. The pattern that works: run stock down before the move where possible (lower closing inventory means less to transfer), settle accounts with existing suppliers before the move, set up new supplier accounts for the new site.</p>
<p>For brewery-tied properties, the brewery account either transfers with the operator (if you&rsquo;re moving to a tied site within the same brewery group) or closes at the old site and opens at the new site. Confirm in writing with the brewery 4&ndash;6 weeks ahead of move day. Tied-house contracts have specific notice requirements and minimum-purchase obligations that affect the closing-stock calculation.</p>
<p>For free houses, the wine and spirit stock transfers with the operator. Wine stock is condition-sensitive &mdash; the storage during transit matters more than for most categories. The wine fridge, the cellar, and the back-bar storage all need temperature management during the move. For higher-end wine collections (above &pound;10,000), specialist wine-transport firms are the right answer rather than general removal.</p>
<p>For food stock, fresh and frozen products are usually run down to zero before move day. Dry goods (spirits, sealed condiments, packaged dry goods) can transfer normally. The food hygiene registration with the new local council is separate from the licensing process and runs on its own timeline.</p>
<p>For till and EPOS system transfers, plan the IT side carefully. The till system at the new site needs to be commissioned with the existing menu and pricing structure before the first service. Most modern EPOS systems are cloud-based so the migration is straightforward; older till-roll systems may need physical replacement at the new site.</p>"""),
    'moving-day-step-by-step-guide.html':
        ('Special-case move days — what changes',
         """<p>The standard moving-day pattern (7am depot, 8am at property, midday load complete, 1pm chain transition, 5pm finished) applies to most routine moves but several scenarios change the timing meaningfully.</p>
<p><strong>Long-distance moves</strong> (London-to-Sussex, Sussex-to-the-North): the depot departure shifts earlier &mdash; sometimes 6am for an 8am arrival at the loading property. The transit takes 2&ndash;4 hours rather than 30&ndash;60 minutes. The unload may run into the evening or split across two days. The <a href=\"moving-from-london-to-sussex.html\">London-to-Sussex guide</a> covers the route-specific timings.</p>
<p><strong>International moves</strong>: the &ldquo;move day&rdquo; is actually a multi-day process. Pack and load at the property over 1&ndash;2 days, customs processing over 3&ndash;5 days, sea or land transit, customs processing at the destination, local delivery. The customer&rsquo;s involvement is concentrated at the start and the end; the middle is paperwork-driven. See <a href=\"overseas-removals-from-sussex.html\">overseas removals</a>.</p>
<p><strong>Listed-building moves</strong>: the load takes longer because of additional building protection (corner-board, door-frame guards, soft floor coverings). A typical 3-bed listed-building move runs 6&ndash;8 hours rather than 4&ndash;5. The <a href=\"moving-to-listed-building-sussex.html\">listed-building moves guide</a> covers the wider considerations.</p>
<p><strong>Office moves</strong>: typically run Friday evening through Sunday rather than a single weekday. The <a href=\"business-office-relocation.html\">office relocation guide</a> covers the after-hours pattern.</p>
<p><strong>Care-home moves</strong>: span multiple days with phased resident transfers. The <a href=\"care-home-relocation-guide.html\">care-home guide</a> covers the multi-day pattern.</p>
<p>For any non-standard move, the timing is in the <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">written quote</a> &mdash; we don&rsquo;t hide the schedule details until move day.</p>"""),
    'overseas-removals-from-sussex.html':
        ('Insurance, customs and the cost-versus-protection question',
         """<p>For international removals specifically, the insurance arrangements are different from domestic moves. Standard UK <a href=\"../terms-conditions-and-insurance-details.html\">goods-in-transit insurance</a> covers the UK leg of the journey but typically excludes the international shipping portion. The FIDI-network partner&rsquo;s insurance covers the shipping and destination handling. For genuinely high-value international contents, a specialist marine cargo insurance policy is the right approach.</p>
<p>The insurance categories: <strong>marine cargo</strong> (covers contents during sea or air shipping), <strong>warehouse-to-warehouse</strong> (extends cover to door-to-door including land transit at both ends), <strong>all risks vs named perils</strong> (all risks is broader; named perils is cheaper but excludes some categories). For most household-content international moves, all-risks warehouse-to-warehouse is the right standard.</p>
<p>Customs duty calculations depend on the destination country. For settled emigration (permanent move, intent to remain in the destination country for at least 12 months), most countries waive duty on used household effects subject to specific paperwork. For temporary residence or returning to a previous country of residence, the duty calculation is different. The FIDI-network partner handles the specific calculation.</p>
<p>For restricted items, every destination country has its own list. Common restrictions: firearms (always need specific paperwork), alcohol (quantity limits in many countries), medications (require prescription paperwork in some destinations), food (most countries restrict or prohibit). Get the destination country&rsquo;s prohibited-items list before packing &mdash; we&rsquo;ll provide it at <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey</a> based on your destination.</p>
<p>For genuinely valuable single items (art, antiques, jewellery), specialist arrangements may be appropriate. The FIDI-network includes art-specialist member firms for the major destinations. Talk to us at survey if your shipment includes individually high-value items.</p>"""),
    'school-holiday-moves.html':
        ('Pre-move and post-move school admin',
         """<p>The school-side admin around a move has hard deadlines that don&rsquo;t flex for the family&rsquo;s convenience. <strong>Pre-move admin</strong>: notify the current school of the leaving date in writing at least 4 weeks ahead. Request the pupil&rsquo;s academic records, including current term reports, attendance records, and any SEN (Special Educational Needs) documentation. The records typically follow to the new school within 2&ndash;4 weeks of the request.</p>
<p><strong>New-school application</strong>: apply through the new local authority&rsquo;s coordinated admissions process. The major deadlines are 15 January (for the September primary intake the same year) and 31 October (for the September secondary intake the following year). Mid-year transfers happen outside these dates and are subject to place availability at the specific schools you want.</p>
<p>For families moving into the <a href=\"moving-to-eastbourne-area-guide.html\">Eastbourne</a> or <a href=\"moving-to-brighton-area-guide.html\">Brighton</a> area, the catchment systems differ. East Sussex uses straightforward distance-based catchments; Brighton & Hove uses a lottery-with-priority system. The <a href=\"best-schools-eastbourne-families.html\">Eastbourne schools guide</a> covers the local admissions specifics.</p>
<p><strong>Post-move admin</strong>: register the children with a new GP and dentist in the first week of arriving. Update the school admin with any new emergency contacts or medical conditions specific to the new house (eg, new address for school-bus pickup). For children with SEN, the new school&rsquo;s SENCo should receive the documentation before the child starts.</p>
<p>For mid-year transfers specifically, contact the receiving school directly. The school can usually arrange a settling-in visit before the formal start date, plus introduce the child to a designated buddy in the new class. Most schools manage mid-year arrivals well; the pastoral team is the right contact point.</p>"""),
    'spring-clean-while-moving.html':
        ('Outdoor categories — garden, garage, sheds',
         """<p>The categories most underestimated in the combined spring-clean-and-move are the outdoor ones. <strong>Garden</strong>: the leaves, the moss on the patio, the gutters that have accumulated debris over winter, the garden furniture that&rsquo;s been sitting out. For owner-moves, leaving the garden in tidy condition matters for the new buyer&rsquo;s first impression. For tenancy-end moves, garden maintenance is often a contractual requirement.</p>
<p><strong>Garage</strong>: the floor with oil spots, the walls covered in dust, the corners full of cobwebs, the workbench layered in years of accumulated debris. An hour with a stiff brush plus a degreasing product for any oil stains transforms a garage from &ldquo;needs deep clean&rdquo; to &ldquo;clean and tenantable&rdquo;.</p>
<p><strong>Garden shed</strong>: the inside is usually worse than the outside. Spider colonies, mouse droppings (rare but happens), accumulated dust, the kit you stored over winter that you forgot was there. Empty the shed, clean it, decide what comes with you and what gets disposed of. The <a href=\"how-to-downsize-before-moving.html\">downsizing guide</a> covers the practical disposal logistics.</p>
<p><strong>Greenhouse</strong>: glass panels both sides, gutters and drainage, the staging shelves. A clean greenhouse extends meaningfully to the property&rsquo;s perceived value at viewing time. A neglected one signals broader neglect.</p>
<p><strong>Outdoor furniture and play equipment</strong>: pressure-wash and dry; cover for winter or transport with the move. Outdoor furniture in good condition is a real asset at the new property; outdoor furniture beyond cleaning is best disposed of before the move rather than transported.</p>
<p><strong>Hard standing</strong>: patios, driveways, paths. The pressure-wash difference between &ldquo;hasn&rsquo;t been done in years&rdquo; and &ldquo;recently cleaned&rdquo; is dramatic. Hire a pressure-washer for a day for &pound;30&ndash;&pound;60, or pay for a professional cleaner if you don&rsquo;t fancy the work.</p>"""),
    'student-move-tips-for-parents.html':
        ('Insurance, security and the first-term financial setup',
         """<p>Student-specific considerations beyond the physical move. <strong>Insurance</strong>: contents insurance for student property. Many parents add the student to their home contents insurance under the &ldquo;personal possessions away from home&rdquo; clause; check the policy limit and the per-item caps. For students with valuable items (laptops, musical instruments, professional camera equipment), specific student contents insurance from providers like Endsleigh or Cover4Students is usually the better option.</p>
<p><strong>Security</strong>: locks, alarms, valuables. Students in private accommodation should have working door and window locks. Valuables (laptops, tablets, smartphones, bicycles) need security marking with the student&rsquo;s details; UK Immobilise is the national property register and worth using. The local police force usually offers free security advice to incoming students.</p>
<p><strong>Bicycle security</strong>: a real concern in university towns. Buy a proper D-lock (not a cable lock), register the bike at UK Immobilise, lock the bike through both wheels and frame to an immovable object. Bike theft from students is one of the most common university-area crimes.</p>
<p><strong>First-term finances</strong>: ensure the student has a working bank account in the destination town (transferring from a parent&rsquo;s area can avoid surcharges in some cases), Council Tax exemption documented (full-time students are exempt &mdash; the university provides the documentation), and access to the student loan in the first week of term.</p>
<p><strong>Settling-in conversations</strong>: the first three weeks at university are when the homesickness sometimes hits. Pre-arrange a phone-call schedule with the student so they know they&rsquo;ll hear from family at predictable times. Most students settle within the first month; the small minority who don&rsquo;t usually benefit from the university&rsquo;s pastoral support, which the personal tutor can connect them to.</p>"""),
    'sustainable-removals-guide.html':
        ('How we run a sustainable Sussex removal in practice',
         """<p>Beyond customer-side decisions, the firm-side practices matter. Here&rsquo;s what we do at Mark Ratcliffe Moving that contributes to lower per-move environmental impact.</p>
<p><strong>Lorry maintenance and efficiency</strong>: regular servicing, properly-inflated tyres, eco-driving training for crew. A well-maintained 7.5-tonne lorry uses 5&ndash;8% less diesel than a poorly-maintained one over the same route. Across thousands of moves a year, this matters.</p>
<p><strong>Reusable blanket inventory</strong>: our pad-wrap blankets are washed between every job and reused indefinitely. The same blanket may wrap a hundred different households&rsquo; furniture over its working life. We&rsquo;d use shrink-wrap instead if we wanted lower materials cost; we don&rsquo;t because the environmental and damage-rate cost is too high.</p>
<p><strong>Carton circulation</strong>: we collect empty cartons from customers after the move (free of charge within standard delivery range) and reuse them on the next job. A removal-grade carton typically does 3&ndash;5 moves before retirement.</p>
<p><strong>Route planning</strong>: we co-load lorries where possible (multiple smaller jobs combined into a single lorry route), direct routes rather than depot-detour routes, and avoid unnecessary trips. The <a href=\"../about-us.html\">Lower Dicker depot</a> is positioned on the A22 specifically to reduce route inefficiency.</p>
<p><strong>Depot energy</strong>: the depot is reasonably efficient by industry standards. We&rsquo;ve invested in lighting controls, insulation, and ventilation efficiency over the years. Solar panels are on the roadmap but not yet installed.</p>
<p><strong>Materials sourcing</strong>: cardboard cartons from recycled content where available, packing tissue from FSC-certified sources, blankets washed in low-impact detergents. None of these decisions are revolutionary individually; in combination they shift the per-move footprint meaningfully versus an unoptimised baseline.</p>
<p>For customers who want to know their specific move is being handled with sustainability in mind, talk to us at <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">survey</a>. We&rsquo;ll explain which decisions matter most for your particular job and which choices are within your control versus ours.</p>"""),
    'ways-to-save-on-house-move.html':
        ('Six more cost-savers that aren&rsquo;t obvious',
         """<p>Beyond the obvious savers (timing, decluttering, self-pack), six less-discussed approaches that genuinely save money.</p>
<p><strong>1. Use the depot collect-empties service.</strong> Most reputable removers collect empty cartons free of charge after the move within standard delivery range. Use this rather than paying for cartons multiple times if you move again within a few years.</p>
<p><strong>2. Get the survey done in person, not by video.</strong> Video surveys are faster but less accurate. In-home surveys catch the loft contents, the under-stair cupboard, the items still being decided about. Better surveys produce more accurate quotes which means less chance of on-day surcharges.</p>
<p><strong>3. Coordinate the chain timing.</strong> A move where the chain completes at noon and the lorry arrives at 8am works smoothly. A move where the chain slips by 3 hours costs nothing extra but stresses everyone. Push your conveyancer for realistic completion timings rather than optimistic ones.</p>
<p><strong>4. Read the contract end-to-end.</strong> Most disputes happen because of contractual misunderstandings. Read what&rsquo;s included (pad-wrap, materials, insurance), what isn&rsquo;t (specialist handling, oversize items, customs paperwork), what the cancellation terms are, and what happens if the chain slips.</p>
<p><strong>5. Use the post-move services your remover offers.</strong> Empty-carton collection, basic furniture reassembly, removal of packing materials &mdash; all included on most full removals at no extra cost. Many customers don&rsquo;t realise these are included.</p>
<p><strong>6. Don&rsquo;t bargain on the wrong things.</strong> Save on volume (declutter), timing (off-peak), and packing tier (fragile-only). Don&rsquo;t save on insurance, pad-wrap standard, or crew training. The categories where false economy bites hardest are the ones that protect your contents; the categories that scale with volume are where genuine savings exist.</p>
<p>The combination of these tactics typically saves 20&ndash;30% on the headline quote without any compromise on the move-day experience. For specific advice on your move, the <a href=\"../mark-ratcliffe-moving-online-removals-quote.html\">free survey</a> covers what saves money in your particular situation.</p>"""),
}

import re
faq_open = re.compile(r'(\s*)<section class="np-section np-faq">')
n = 0
for slug, (heading, body) in EXTRAS.items():
    path = 'blog/' + slug
    if not os.path.isfile(path):
        print(f'  ✗ missing {path}')
        continue
    html = open(path, encoding='utf-8').read()
    block = ('\n  <section class="np-section np-section-soft">\n'
             '    <div class="np-inner">\n'
             f'      <h2>{heading}</h2>\n'
             f'      {body}\n'
             '    </div>\n'
             '  </section>\n')
    new_html, c = faq_open.subn(block + r'\1<section class="np-section np-faq">', html, count=1)
    if c == 1:
        open(path, 'w', encoding='utf-8').write(new_html)
        n += 1
        print(f'  ✓ topped up {slug}')
print(f'Done: {n}')
